[[ -s $HOME/.profile ]] && source $HOME/.profile

[[ $SSH_AGENT_PID -eq "" ]] && eval $(keychain --eval --agents ssh,gpg --quiet ~/.ssh/id_*[^pub])

[[ ! -d "$tmp" ]] && export tmp="/tmp/$USER"
mkdir -p -m 700 "$tmp"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export PLATFORM=`uname -s`

export EDITOR=vi
[[ -s $(which vim) ]] && export EDITOR=vim
[[ -s $(which nvim) ]] && export EDITOR=nvim

# Reduce delay after you hit the <ESC> to 0.2 seconds (hat tip Doug Black)
export KEYTIMEOUT=20

export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000

export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# Adds Node module (LiveScript, Jasmin) binaries into path
[[ -s "$HOME/node_modules" ]] && export PATH=$PATH:$HOME/node_modules/.bin:$HOME/node_modules/bin
