# Aliases
[[ -s ~/.config/zsh/alias.zsh ]] && source ~/.config/zsh/alias.zsh

# Shell prompt always in the bottom of the screen
tput cup $LINES 0

# Disable annoying flow mode, free up C-S and C-Q
stty -ixon -ixoff

# Prevent overwriting existing files with '> filename', use '>| filename' # (or >!) instead.
# Hat tip http://ruderich.org/simon/config/zshrc
setopt noclobber

# Zsh, please...
unsetopt correct_all

# Credit: https://robots.thoughtbot.com/how-to-use-arguments-in-a-rake-task
# Allow [ or ] whereever you want
unsetopt nomatch

# Ignore duplicate history entries
setopt histignoredups

. ~/.zplug/zplug
! zplug check && zplug install
zplug b4b4r07/zplug
zplug zsh-users/zsh-syntax-highlighting
zplug zsh-users/zsh-history-substring-search
zplug djui/alias-tips
# zplug tarruda/zsh-autosuggestions
zplug load

# Better vi mode (hat tip Doug Black)
bindkey -v
bindkey '^r' history-incremental-search-backward
bindkey -a '^r' history-incremental-search-backward

bindkey -a 'H' beginning-of-line
bindkey -a 'L' end-of-line

# Better undo/redo
bindkey -M vicmd u undo
bindkey -M vicmd U redo

# Switch to command mode. jk or kk or jj are to slow to work with 0.1s timeout
# kjk<CR> to repeat last command
bindkey -M viins kj vi-cmd-mode

# Switch back to fg %1 on ^Z (hat tip Adam Stankiewicz http://sheerun.net/)
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
    zle redisplay
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey -v '^Z' fancy-ctrl-z
bindkey -a '^Z' fancy-ctrl-z

# Edit command in external editor
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# # Autosuggestions
# zle-line-init() {
#   zle autosuggest-start
# }
# zle -N zle-line-init
# bindkey '^f' vi-forward-word

# Color scheme
[[ -s ~/.config/zsh/colors.sh ]] && source ~/.config/zsh/colors.sh
autoload -U colors && colors

# Git prompt
[[ -s ~/.bin/git-prompt.sh ]] && source ~/.bin/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=0

# Prompt

# Expand functions in the prompt
setopt prompt_subst

export PS1='%n@%{$fg[blue]%}%m %{$fg[yellow]%}%~ %{$fg[green]%}%$(__git_ps1) %{$reset_color%}% %(!.#.$) '

# Many programs change the terminal state, and often do not restore terminal settings on exiting abnormally. To avoid the need to manually reset the terminal, freeze it:
ttyctl -f
