# Aliases
[[ -s ~/.config/zsh/alias.zsh ]] && source ~/.config/zsh/alias.zsh

# Shell prompt always in the bottom of the screen
tput cup $LINES 0

# Disable annoying flow mode, free up C-S and C-Q
stty -ixon -ixoff

# Prevent overwriting existing files with '> filename', use '>| filename' # (or >!) instead.
# Hat tip http://ruderich.org/simon/config/zshrc
setopt noclobber

# Zsh, please...
unsetopt correct_all

# Credit: https://robots.thoughtbot.com/how-to-use-arguments-in-a-rake-task
# Allow [ or ] whereever you want
unsetopt nomatch

# Ignore duplicate history entries
setopt histignoredups

# Cache completions
autoload -Uz compinit

source ~/.zplug/init.zsh
zplug check || zplug install
zplug zplug/zplug
zplug zsh-users/zsh-syntax-highlighting
zplug zsh-users/zsh-history-substring-search
zplug djui/alias-tips
zplug tarruda/zsh-autosuggestions
zplug load

# Better vi mode (hat tip Doug Black)
bindkey -v

# Switch to command mode even if in insert mode initially
history-incremental-search-backward-ins () {
  zle history-incremental-search-backward
  zle -K vicmd
}
zle -N history-incremental-search-backward-ins
bindkey ^r history-incremental-search-backward-ins
bindkey -a ^r history-incremental-search-backward
# Accept incremental search for further editing with a single escape
bindkey -M isearch '\e' accept-search
bindkey -M isearch kj accept-search
bindkey -M isearch ^p history-incremental-search-backward
bindkey -M isearch ^n history-incremental-search-forward

bindkey -a 'H' beginning-of-line
bindkey -a 'L' end-of-line

# Use ^F to complete an autosuggestion
bindkey -M viins ff forward-char

# Better undo/redo
bindkey -M vicmd u undo
bindkey -M vicmd U redo

# Switch to command mode. jk or kk or jj are to slow to work with 0.1s timeout
# kjk<CR> to repeat last command
bindkey -M viins kj vi-cmd-mode

# Switch back to fg %1 on ^Z (hat tip Adam Stankiewicz http://sheerun.net/)
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
    zle redisplay
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey -v ^Z fancy-ctrl-z
bindkey -a ^Z fancy-ctrl-z

# Edit command in external editor
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

bindkey -M vicmd K run-help

# Color scheme
[[ -s ~/.config/zsh/colors.sh ]] && source ~/.config/zsh/colors.sh
autoload -U colors && colors

# Prompt

setopt prompt_subst
autoload -Uz vcs_info
zstyle ':vcs_info:*' formats "%b %m%u%c"
zstyle ':vcs_info:*' actionformats "%b %u%c|%a"
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' stagedstr '+'
zstyle ':vcs_info:*' unstagedstr '*'
precmd () { vcs_info }

PS1='%n@%{$fg[blue]%}%m %{$fg[yellow]%}%~ %{$fg[green]%}% (${vcs_info_msg_0_}) %{$reset_color%}% %(!.#.$) '

# Homebrew github api key
[[ -s ~/.config/zsh/brew-api-key.sh ]] && source ~/.config/zsh/brew-api-key.sh

# Many programs change the terminal state, and often do not restore terminal settings on exiting abnormally. To avoid the need to manually reset the terminal, freeze it:
ttyctl -f
