#!/bin/bash

_all() {
  (
    cd $(dirname $2)
    echo $(bash -c "$1" 1>/dev/null 2>&1 && echo "[+]" || echo "[ ]") $(pwd)
  )
}
export -f _all

echo "$*" for all repos
export COMMAND="$*"
fd --hidden --no-ignore --maxdepth 2 '.git$' | xargs -P 10 -L1 -I{} bash -c '_all "$COMMAND" "{}"'
