#!/usr/bin/env sh

# Credit: https://smith.langchain.com/hub/rlm/matt-shumer-writing
#
# I (Phil Pirozhkov) edited the original prompt in the following ways:
#   - removed duplication, it had the same phrases written twice, with slight differences
#   - removed the "three drafts and the final" recommendation: sometimes it worked, sometimes inferrence abruptly ended after the first draft
#   - made the prompt's language more concise and clear
#
# The only necessary configuration is the ~/.config/the-editor/model file, containing the model name to use, e.g.,
# deepseek-r1:14b, llama3.1, or phi4
#
# For additional convenience, I've implemented loading of the context from text files, e.g. "The text is direct and concise".
# There are two contexts that are loaded. One of them is global, and is loaded from ~/.config/the-editor/global-context.txt
# The other one is project-local and is read from the same directory from which the script is run, from ./.the-editor-context file.
# Both contexts are optional to use.
#
# This script will write the text back to facilitate diff'ing. Please mind checking the file to version control before asking the-editor to edit it for you.

# Exit with an error if the file has dirty changes in git. Otherwise, they will be overwritten.
git diff --quiet --exit-code -- "$1" || { echo "The file contains uncommitted changes. The-Editor overwrites the file, and your changes will be lost." ; exit 1 ; }

mkdir -p $XDG_CONFIG_HOME/the-editor

MODEL=$( cat $XDG_CONFIG_HOME/the-editor/model )
[[ -z $MODEL ]] && { echo "Add the model name to use to $XDG_CONFIG_HOME/the-editor/model, e.g.: 'echo deepseek-r1:14b > $XDG_CONFIG_HOME/the-editor/model'" ; exit 1 ; }

ollama run $MODEL << OLLAMA-TEXT > "$1"
Given some TEXT and CONTEXT, improve the text.

Do not rewrite the text entirely. Make some changes to make it better.

Emulate the original text's tone, style, and meaning.

Approach the task like an editor - not a rewriter.

Keep the original, intended meaning.
Don't stray away from the original while editing.

First, write a quick summary of the key points that the original text conveys.

Evaluate the result, and then reflect on how the text can be further improved.

CONTEXT:
---
$( cat $(echo $XDG_CONFIG_HOME)/the-editor/global-context.txt )

$( cat .the-editor-context )
---

TEXT:
---
$( cat "$1" )
---
OLLAMA-TEXT
