#!/bin/bash

COMMIT_MSG_FILE=$1

if [[ "$PWD" == *"/source/emp/"* ]]; then
  if [[ $(cat $COMMIT_MSG_FILE | grep -v '^Merge') == 0 ]]; then
    echo "$(git branch --show-current)$(cat $COMMIT_MSG_FILE)" > "$COMMIT_MSG_FILE"
  fi
fi
